# Use the official Node.js image as a base
FROM node:18 AS build

WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code from current project dir to docker's current dir
COPY . .

# Build the React app for production
RUN npm run build

# Use a lightweight web server to serve the built app
FROM nginx:1.25

# Copy the build output from the previous stage to the web server's default location
COPY --from=build /app/build /usr/share/nginx/html

# Expose the default port used by the Nginx web server
EXPOSE 80

# Start the Nginx server
CMD ["nginx", "-g", "daemon off;"]
